# Generated by Django 5.2.6 on 2025-12-02 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16)),
                ('cardholder_name', models.CharField(max_length=100)),
                ('cvv', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstColor', models.CharField(max_length=20)),
                ('secondColor', models.CharField(max_length=20)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='api.card')),
            ],
        ),
        migrations.CreateModel(
            name='Expiration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=5)),
                ('year', models.CharField(max_length=5)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='date_expiration', to='api.card')),
            ],
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
