# Generated by Django 5.2.6 on 2025-12-02 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_card_colors_expiration_delete_blogpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='cardholder_name',
            new_name='card_holder',
        ),
    ]
