# Generated by Django 5.2.6 on 2025-12-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_cardholder_name_card_card_holder'),
    ]

    operations = [
        migrations.AddField(
            model_name='colors',
            name='textColor',
            field=models.CharField(default='black', max_length=20),
        ),
    ]
